name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Cloudflare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set runner timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"

      - name: Install dependencies
        run: npm install

      - name: Build static files
        run: npm run build
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=habichuela --commit-dirty=true
